CEdu/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from CEdu import views
urlpatterns=[
	url(r'^$',views.index,name='index'),
	url(r'^about$',views.about,name='about'),
	url(r'^contact$',views.contact,name='contact'),
]

edu/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from CEdu import urls as CEdu_urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cedu/',include(CEdu_urls,namespace='CEdu')),
]

CEdu/models.py
from django.db import models

# Create your models here.

CEdu/views.py
#coding=utf-8
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.core.urlresolvers import reverse
def index(req):
	return render(req,'index.html')
def contact(req):
	return render(req,'contact.html')
def about(req):
	return render(req,'about.html')
# Create your views here.

CEdu/templates/about.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title></title>
<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/bootstrap.min.css' %} " type="text/css">
<!-- Dropdownhover CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/bootstrap-dropdownhover.min.css' %} " type="text/css">
<!-- fonts awesome -->
<link rel="stylesheet" href=" {% static 'assets/font/css/font-awesome.min.css' %} " type="text/css">
<!-- Plugin CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/animate.min.css' %} " type="text/css">
<!-- Custom CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/style.css' %} " type="text/css">
<!-- Owl Carousel Assets -->
<link href=" {% static 'assets/owl-carousel/owl.carousel.css' %} " rel="stylesheet">
<link href=" {% static 'assets/owl-carousel/owl.theme.css' %} " rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src=" {% static 'libs/html5shiv/3.7.0/html5shiv.js' %} "></script>
  <script src=" {% static 'libs/respond.js/1.4.2/respond.min.js' %} "></script>
  <![endif]-->
</head>

<body>

 

<!-- Preloader -->
<div id="preloader">
	<div id="loading">
	</div>
</div>
<header class="insid-header">
	<!-- top-menu -->
	<div class="top-menu">
		<!-- top-header -->
		<div class="top-header">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 col-sm-6 col-md-6">
						<div class="phone dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i class="fa fa-globe" aria-hidden="true"></i> Language : English </a>
							 <ul class="dropdown-menu">
								 <li><a href="#">English</a></li>
								<li><a href="#">Aribce</a></li>
							</ul>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-6">
						<div class="social">
							<ul>
								<li><a href="#">Log In</a></li>
								<li>|</li>
								<li><a href="#">Sign up</a></li>
								<li>|</li>
								<li><a href="#">Register</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

		</div>
		<!-- /top-header -->
		<!-- mainNav -->
		<div id="mainNav" class="navbar-fixed-top">
			<div class="container">
				<div class="row">
					<nav class="navbar navbar-inverse navbar-default">

						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<a class="navbar-brand" href="#"><img src=" {% static 'assets/img/logo.png' %} " alt="logo"></a>
						</div>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1" data-hover="dropdown" data-animations="fadeIn fadeInLeft fadeInUp fadeInRight">
							<ul class="nav navbar-nav">
								<li><a href=" {% url 'CEdu:index' %} ">Home</a></li>
								<li><a href=" # ">About Us</a></li>
								<li><a href=" {% url 'CEdu:contact' %} "><span>Contact</span></a></li>
								<li>
									<a href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
								</li>
							</ul>
							<!-- /.navbar-collapse -->
						</div>

					</nav>
				</div>
			</div>


		</div>
		<!-- /mainNav -->
	</div>
	<!-- /top-menu -->
	<!-- header-title -->
	<div class="header-title">
		<h1>About Us</h1>
	</div>
	<!-- /header-title -->
</header>
<section class="courses">
	<!-- .courses -->
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12">
				<!-- .about-text1 -->
				<div class="about-text1 text-center">
					<h2>We Are <span>E-LEARNING</span></h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec diam lectus, fermentum ac sem vitae, ultrices mattis urna. Mauris diam elit, fringilla sit ame venenatis sed, porttitor nec tellus. Pellentesque tempus purus odio, id commodo ligula sodales nec. Fusce rutrum tincidunt consectetur. In vel orci venenatis sed, porttitor nec tellus. Pellentesque tempus purus odio, id commodo ligula sodales nec. Fusce rutrum tincidunt consectetur. In vel orci tristique,aliquam nisi non, rutrum mi. Cras feugiat ultrices lobortis. Nullam ut tincidunt tortor</p>
				</div>
				<!-- /.about-text1 -->
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6">
				<div class="our-course">
					<h3>Our Course Plan</h3>
					<ul>
						<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
						<li>Nullam sed lorem id sapien vulputate viverra eget quis magna.</li>
						<li>Donec et dolor et turpis fermentum semper vitae eu nisl.</li>
						<li>Ut tristique enim at metus hendrerit luctus.</li>
						<li>Fusce vel risus tempus, scelerisque enim non, tincidunt risus.</li>
						<li>Sed fermentum velit in lacus fringilla, ut varius leo efficitur.</li>
						<li>Morbi ullamcorper orci eu nunc suscipit luctus.</li>
						<li>In consequat sapien in enim dictum, eget tempor magna convallis.</li>
						<li>Morbi vulputate purus at est ultrices posuere.</li>
					</ul>
				</div>	
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6">
				<img src=" {% static 'assets/img/about-img.jpg' %} " alt="about img">
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12">
				<!-- .about-text1 -->
				<div class="about-text3 text-center">
					<h3>Our Successful Story</h3>
					<p>me aristMaecenas egestas, est in tempor porttitor, enim felis euismod metus, a varius neque ex non magna. Nulla lacinia dictum est, a tempus justo consequa 
Nulla posuere sit amet nibh vitae vehicula. Donec varius sollicitudin turpis id sollicitudin. Pellentesque accumsan laoreet urna, non suscipit orci lobortis sit amet.
Nulla laoreet metus augue, quis porta tellus finibus non. Curabitur nec scelerisque eroMaecenas egestas, est in tempor porttitor, enim felis euismod met
a varius neque ex non magna. Nulla lacinia dictum est, a tempus justo consequat et. Nulla posuere sit amet nibh vitae vehicula. Donec varius sollicitudin tu
rpis id sollicitudin. Pellentesque accumsan laoreet urna, non suscipit orci lobortis sit amet. Nulla laoreet metus augue, quis porta tellus finibus non.
urabitur nec scelerisque eroMaecenas egestas, est in tempor porttitor, enim felis euismod.</p>
				</div>
				<!-- /.about-text1 -->
			</div>
		</div>
	</div>
	<!-- /.courses -->
</section>


<section class="px-bg2">
	<!-- .Subscribe -->
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="subscribe">
					<h2>120+ classes & Staff Teaching<br/>Courses and Discussing Topics Online</h2>
					<a href="#" class="button">Subscribe Now</a>
				</div>
			</div>
		</div>
	</div>
	<!-- /.Subscribe -->
</section>


<!-- START FOOTER SECTION -->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="flog"><img src=" {% static 'assets/img/logo.png' %} " alt="f-logo" /></div>
			</div>
			<div class="col-12-12 col-sm-6 col-md-6">
				<span class="address">123, Radio Station, San francisco<br>
				 1234, new sm street<br>
				 San francisco</span>
			</div>
			<div class="col-12-12 col-sm-6 col-md-6">
				<span class="phone">Phone : +000 123 456 789<br>
					Fax : 11.880.000<br>
					E-mail: Info@example.cp,m</span>
			</div>
			<div class="col-md-12">
				<div class="f-sicon">
					<h2>FOLLOW US ON</h2>
					<ul>
						<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
						<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
						<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
						<li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
					</ul>
				</div>
				<div class="copyright">
					Copyright &copy; 2017.Company name All rights reserved.<a target="_blank" href=" {% static 'http://sc.chinaz.com/moban/' %} ">&#x7F51;&#x9875;&#x6A21;&#x677F;</a>
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- jQuery -->
<script src=" {% static 'assets/js/jquery.js' %} "></script>
<!-- Bootstrap Core JavaScript -->
<script src=" {% static 'assets/js/bootstrap.min.js' %} "></script>
<script src=" {% static 'assets/js/bootstrap-dropdownhover.min.js' %} "></script>
<!-- Plugin JavaScript -->
<script src=" {% static 'assets/js/jquery.easing.min.js' %} "></script>
<script src=" {% static 'assets/js/jquery.fittext.js' %} "></script>
<script src=" {% static 'assets/js/wow.min.js' %} "></script>	
<!-- Resource jQuery -->
<!--  countTo JavaScript  -->
<script type="text/javascript" src=" {% static 'assets/js/jquery.countTo.js' %} "></script>
<!-- owl carousel -->
<script src=" {% static 'assets/owl-carousel/owl.carousel.js' %} "></script>
<!--  Custom Theme JavaScript  -->
<script src=" {% static 'assets/js/custom.js' %} "></script>
</body>

</html>

CEdu/templates/contact.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title></title>
<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/bootstrap.min.css' %} " type="text/css">
<!-- Dropdownhover CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/bootstrap-dropdownhover.min.css' %} " type="text/css">
<!-- fonts awesome -->
<link rel="stylesheet" href=" {% static 'assets/font/css/font-awesome.min.css' %} " type="text/css">
<!-- Plugin CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/animate.min.css' %} " type="text/css">
<!-- Custom CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/style.css' %} " type="text/css">
<!-- Owl Carousel Assets -->
<link href=" {% static 'assets/owl-carousel/owl.carousel.css' %} " rel="stylesheet">
<link href=" {% static 'assets/owl-carousel/owl.theme.css' %} " rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src=" {% static 'libs/html5shiv/3.7.0/html5shiv.js' %} "></script>
  <script src=" {% static 'libs/respond.js/1.4.2/respond.min.js' %} "></script>
  <![endif]-->
</head>

<body>
 


<!-- Preloader -->
<div id="preloader">
	<div id="loading">
	</div>
</div>
<header class="insid-header">
	<!-- top-menu -->
	<div class="top-menu">
		<!-- top-header -->
		<div class="top-header">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 col-sm-6 col-md-6">
						<div class="phone dropdown">
							<a href=" # " class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i class="fa fa-globe" aria-hidden="true"></i> Language : English </a>
							 <ul class="dropdown-menu">
								 <li><a href=" # ">English</a></li>
								<li><a href=" # ">Aribce</a></li>
							</ul>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-6">
						<div class="social">
							<ul>
								<li><a href=" # ">Log In</a></li>
								<li>|</li>
								<li><a href=" # ">Sign up</a></li>
								<li>|</li>
								<li><a href=" # ">Register</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

		</div>
		<!-- /top-header -->
		<!-- mainNav -->
		<div id="mainNav" class="navbar-fixed-top">
			<div class="container">
				<div class="row">
					<nav class="navbar navbar-inverse navbar-default">

						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<a class="navbar-brand" href=" # "><img src=" {% static 'assets/img/logo.png' %} " alt="logo"></a>
						</div>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1" data-hover="dropdown" data-animations="fadeIn fadeInLeft fadeInUp fadeInRight">
							<ul class="nav navbar-nav">
								<li><a href=" {% url 'CEdu:index' %} ">Home</a></li>
								<li><a href=" {% url 'CEdu:about' %} ">About Us</a></li>
								<li><a href="#"><span>Contact</span></a></li>
								<li>
									<a href=" # "><i class="fa fa-search" aria-hidden="true"></i></a>
								</li>
							</ul>
							<!-- /.navbar-collapse -->
						</div>

					</nav>
				</div>
			</div>


		</div>
		<!-- /mainNav -->
	</div>
	<!-- /top-menu -->
	<!-- header-title -->
	<div class="header-title">
		<h1>Contact Us</h1>
	</div>
	<!-- /header-title -->
</header>
<section class="courses">
				  <!-- The element that will contain our Google Map. This is used in both the Javascript and CSS above. -->
	 <div id="map"></div>
	 <!-- /map end -->
	<!-- .courses -->
	<div class="container">
		<div class="row">		
			<div class="contact-outer">
			<div class="col-xs-12 col-sm-8 col-md-8">
				<div class="our-course">
					<form name="ajax-form" id="contact-form2" action="" method="post" class="contact-form">
						<input name="_redirect" id="name2" value="contact.html" type="hidden">
						<div class="col-sm-12 col-md-12"><h2>GET IN TOUCH</h2></div>
						<div class="col-sm-12 col-md-12">
							<input id="name" name="first-name" required="" placeholder="First Name" type="text">
						</div>
						<div class="col-sm-12 col-md-12">
							<input id="email" name="email" required="" placeholder="Your Email" type="email">
						</div>
						<div class="col-sm-12 col-md-12">
							<input id="suject" name="suject" required="" placeholder="Your suject" type="text">
						</div>
						<div class="col-md-12">
							<textarea id="comment" name="comment" cols="45" rows="5" placeholder="Type your message here..." aria-required="true"></textarea>
						</div>
						<div class="col-sm-12 col-md-12 text-center">
							<input name="submit" value="Submit" id="send" type="submit">
						</div>
					</form>
				</div>
			</div>
			<div class="col-xs-12 col-sm-4 col-md-4">
				<div class="contact-info">
				<h2>CONTACT US</h2>
				<ul>
				 <li>
					<div class="icon"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
					<div class="ftext">31 Street Lane, 4th
					   Floor, NY 23560
					</div>
				 </li>                     
				 <li>
					<div class="icon"><i class="fa fa-envelope" aria-hidden="true"></i></div>
					<div class="ftext">info@sitename.com</div>
				 </li>
				<li>
					<div class="icon"><i class="fa fa-phone" aria-hidden="true"></i></div>
					<div class="ftext">+8807. 325. 2145</div>
				 </li>
			  </ul>
				</div>				 	
			</div>
			</div>	
		</div>
	</div>
	<!-- /.courses -->
</section>
<!-- START FOOTER SECTION -->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="flog"><img src=" {% static 'assets/img/logo.png' %} " alt="f-logo" /></div>
			</div>
			<div class="col-12-12 col-sm-6 col-md-6">
				<span class="address">123, Radio Station, San francisco<br>
				 1234, new sm street<br>
				 San francisco</span>
			</div>
			<div class="col-12-12 col-sm-6 col-md-6">
				<span class="phone">Phone : +000 123 456 789<br>
					Fax : 11.880.000<br>
					E-mail: Info@example.cp,m</span>
			</div>
			<div class="col-md-12">
				<div class="f-sicon">
					<h2>FOLLOW US ON</h2>
					<ul>
						<li><a href=" # "><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href=" # "><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href=" # "><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
						<li><a href=" # "><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
						<li><a href=" # "><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
						<li><a href=" # "><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
					</ul>
				</div>
				<div class="copyright">
					Copyright &copy; 2017.Company name All rights reserved.<a target="_blank" href=" {% static 'http://sc.chinaz.com/moban/' %} ">&#x7F51;&#x9875;&#x6A21;&#x677F;</a>
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- jQuery -->
<script src=" {% static 'assets/js/jquery.js' %} "></script>
<!-- Bootstrap Core JavaScript -->
<script src=" {% static 'assets/js/bootstrap.min.js' %} "></script>
<script src=" {% static 'assets/js/bootstrap-dropdownhover.min.js' %} "></script>
<!-- Plugin JavaScript -->
<script src=" {% static 'assets/js/jquery.easing.min.js' %} "></script>
<script src=" {% static 'assets/js/jquery.fittext.js' %} "></script>
<script src=" {% static 'assets/js/wow.min.js' %} "></script>
<script src=" {% static 'assets/js/modernizr.js' %} "></script>
<!-- Modernizr -->
<script src=" {% static 'assets/js/main.js' %} "></script>
<!-- Resource jQuery -->
<!--  countTo JavaScript  -->
<script type="text/javascript" src=" {% static 'assets/js/jquery.countTo.js' %} "></script>
<!-- owl carousel -->
<script src=" {% static 'assets/owl-carousel/owl.carousel.js' %} "></script>
<!--  Custom Theme JavaScript  -->
<script src=" {% static 'assets/js/custom.js' %} "></script>

	
</script>
  <script src=" {% static 'assets/js/map.js' %} "></script> 
</body>

</html>